# FROM ushuaia/pymupdf:1.21.1
FROM python:3.12.0-bookworm
# FROM python:3.7
WORKDIR /app
COPY ./* .

# RUN apt-get update && ls
# RUN apt-get update && \
    # pip3 install -r requirements.txt
    

ENTRYPOINT ["tail", "-f", "/dev/null"]